### ISSUE TITLE
libopus.so.0 not found on ARM Debian system

### ISSUE THREAD

**Issue by milandamen** [Phxntxm/Bonfire#19]
In cogs/music.py on line 18, libopus.so.0 is trying to be located at `/usr/lib64/`, but for my system it was in `/usr/lib/arm-linux-gnueabi/`. There should be a way of detecting this automatically.

**Comment by Phxntxm** [comment]
https://github.com/Rapptz/discord.py/blob/async/discord/opus.py#L86

It already does. The line in my file is an attempt to load it from a rather normal spot, if the library has failed to do so automatically.
