### ISSUE TITLE
Bonfire doesn't remember her volume!

### ISSUE THREAD

**Issue by Raeyn** [Phxntxm/Bonfire#20]
When Bonfire leaves a channel, she resets her volume to 100%.

Not only does this mean that we have to constantly readjust the volume any time Bonfire is summoned, considering how loud 100% Bonfire is (we usually run her on around 7%), this blows the eardrums of anyone who hasn't adjusted her volume manually in the past/is new to the channel.

Could we please have Bonfire remember her nice volume?

**Comment by Phxntxm** [comment]
github issues aren't really for suggestions; since you already suggested this in the discord server I'll close this.
