### ISSUE TITLE
!poll doesnt give active poll

### ISSUE THREAD

**Issue by Liquidmasl** [Phxntxm/Bonfire#23]
just states that more information is needed to make a new one!

**Comment by Phxntxm** [comment]
That's correct

**Comment by Liquidmasl** [comment]
but wiki says "Provides all currently "running" strawpolls on this server" 

did i misunderstood that?

**Comment by Liquidmasl** [comment]
so then how to i get all active polls? or the last one?

**Comment by Phxntxm** [comment]
That wiki is super out of date, there is no way to "view polls" through the bot. It is simply a message it sends when the poll is started, typically a user puts that in a specific channel so it can be followed is the poll needs to last a while

**Comment by Liquidmasl** [comment]
i see, okay, is there an updated version of the wiki hidden somewhere? is the !help command up to date?

thanks for your work btw, I would love to see werewolf as a game, maybe i will try to implement it somewhen

**Comment by Phxntxm** [comment]
No there's no wiki, yes the help is up to date. What the heck is "werewolf" as a game?

**Comment by Liquidmasl** [comment]
its a game you can play with a group of people, there is a version to buy, i just found on google, but thats not needed, its really simple to do with a sheet of paper when sitting together, so its also really easy in code!

here is the version to buy: https://www.playwerewolf.co/rules/

here a wiki: http://werewolf-the-game.wikia.com/wiki/Main_Page

but there are easier ways to do, i am coding myself so maybe i will contribute in the future, Uni is taking to much time at the moment.
But this would be really awsome!

I dont think there is a bot doing this at the moment, so this would be really cool.
